### PR TITLE
autotune for cuda tx2 resnet50 models

### PR DESCRIPTION
**Pull request by apivovarov**
Jetson tx2 fails to run resnet50_v1 and resnet50_v2 mxnet models if the model was compiled by the latest tvm with original cuda_v0.04.log file.
`CUDALaunch Error: CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES`
Discussion: https://discuss.tvm.ai/t/got-error-on-jetson-tx2-with-resnet50-v2-cuda-out-of-resources

As recommended in the discussion I run autotvm for resnet50_v1 and resnet50_v2 mxnet models for Jetson TX2 and got 27 new log lines. (26 topi_nn_conv2d and 1 topi_nn_dense)
This PR replaces corresponding log lines from original cuda_v0.04.log with new 27 new lines. (23 lines were replaced and 4 added)

resnet50 mxnet models compiled with new cuda_v0.04.log file work fine on Jetson TX2.
exec time:
```
tx2 cuda_v0.04.log resnet50_v1 float32: Mean inference time (std dev): 29.61 ms (0.66 ms)

tx2 cuda_v0.04.log resnet50_v2 float32: Mean inference time (std dev): 32.89 ms (0.66 ms)

$ md5sum cuda_v0.04.log
732cacf2fd3b138e223aa8a5773665aa  cuda_v0.04.log
$ wc -l cuda_v0.04.log
486 cuda_v0.04.log
```

Jetson TX2 has JetPack 4.2 with Cuda 10.0
TVM commit - Apr 9, 06347782a36e07094443b22a80b74e302f599d0b

### CODE REVIEW

**Comment by eqy** [comment]
This looks good, can you comment on the tuning strategy (e.g., tuner, number of trials, early stopping) used? (so we have a reference point in case someone wants to retune later on)

**Review by eqy — APPROVED** [review]

**Comment by apivovarov** [comment]
```
tuning_options:
    'tuner': 'xgb',
    'n_trial': 1000,
    'early_stopping': 600,

try_winograd=True
try_spatial_pack_depthwise=True
spatial_pack_tuner = 'xgb_knob'
```

**Comment by eqy** [comment]
@merrymercy can you merge this in?
(I don't have write access)

**Comment by apivovarov** [comment]
I also generated autotvm logs for resnet 18 and 34 models (it replaces another 6 tx2 log lines in original cuda_v0.04.log file)
With this change resnet 18 and 34 inference works 24-25% faster than with original cuda_v0.04.log file on Jetson TX2

**Comment by merrymercy** [comment]
Thanks @apivovarov @eqy  It is merged

**Comment by tqchen** [comment]
Maybe we need to revert some of this because of https://discuss.tvm.ai/t/solved-python-2-3-relay-build-gives-error-nonetype-object-is-not-subscriptable/2248/2

**Comment by tqchen** [comment]
@merrymercy please look a bit into it

**Comment by merrymercy** [comment]
The `topi_nn_dense` line is wrong. @apivovarov  Is it due to some of your local change?
I will just delete that line

**Pull request merged**
